### PR TITLE
Create flutter.org

### PR DESCRIPTION
**Pull request by IwoHerka**

### CODE REVIEW

**Comment by maticomp** [comment]
@IwoHerka Just to confirm, as I assume that's the case: are these resources uniformly referring to Flutter 2 _or_ are universally applicable to both 2 and earlier versions?

Otherwise, nice set!

**Review by dragonee — COMMENTED** [review]
Can you at this moment provide some a memo how one should approach these links? E.g. necessary and suplementary reading, a minimum amount of knowledge to start tinkering with the tutorials etc.?

**Comment by IwoHerka** [comment]
> @IwoHerka Just to confirm, as I assume that's the case: are these resources uniformly referring to Flutter 2 _or_ are universally applicable to both 2 and earlier versions?
> 
> Otherwise, nice set!

They are universal.

**Comment by IwoHerka** [comment]
> Can you at this moment provide some a memo how one should approach these links? E.g. necessary and suplementary reading, a minimum amount of knowledge to start tinkering with the tutorials etc.?

Honestly, I just wanted a nice list of useful links in place, not a guide. I think we could do this down the line, but in a separe pull I think.

**Review by maticomp — APPROVED** [review]
Since @dragonee is away, I'm happy to merge this as-is and update with nice to have's later, just like you suggest.

**Pull request merged**
